###################### Auditbeat Configuration Example #########################

# This is an example configuration file highlighting only the most common
# options. The auditbeat.reference.yml file from the same directory contains all
# the supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/auditbeat/index.html

# =========================== Modules configuration ============================
auditbeat.modules:

- module: file_integrity
  paths:
  - /bin
  - /usr/bin
  - /usr/local
  - /sbin
  - /usr/sbin
  - /usr/local/sbin
  - /Applications
  - /Library
  - /System
- module: system
  datasets:
    - host

  period: 30m # The frequency at which the datasets check for changes
  state.period: 12h
- module: system
  datasets:
    - process
  processors:
    - drop_event.when:
         or:
          - contains.event.action: "existing_process"
          - contains.event.action: "process_error"
    - add_process_metadata:
        match_pids: [process.ppid]
        target: process.parent
  period: 5s


# ================================== General ===================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
name: Finn

# The tags of the shipper are included in their own field with each
# transaction published.
tags: ["macOS"]

# no need to set up the elk stack because it already exists
setup.ilm.enabled: false


# ------------------------------ Logstash Output -------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["b44007d6-3f02-4e87-80fe-b6a99779975b-ls.logit.io:23563"]

# ================================= Processors =================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
